name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_call:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Format check
        run: pnpm run format --check

      - name: Lint
        run: pnpm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Build library
        run: pnpm run build:lib

      - name: Build demo
        run: npx ng build demo

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Test
        run: npx ng test demo --no-watch
